source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

target 'JSPatchDemo' do
pod 'JSPatch'
pod 'AFNetworking'
pod 'MagicalRecord', '~> 2.3.2'
pod 'SDWebImage', '~> 3.8.1'
pod 'MBProgressHUD'
pod 'MJRefresh', '~> 3.1.12'
pod 'SSKeychain'
pod 'SAMKeychain', '~> 1.5.2'
pod 'Masonry', '~> 1.0.2'
pod 'MJExtension', '~> 3.0.13'
end
